[[check]]
type = "Exclude"
id = "STAN-0208"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0212"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0209"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0103"
file = "src/GitLab/API/Projects.hs"
scope = "all"